### ISSUE TITLE
video calling feature

### ISSUE THREAD

**Issue by sai2003a** [sai2003a/expConsult#1]
Implement a video call feature for seamless real-time communication, ensuring high-quality streaming, stability, and cross-browser compatibility. Include user interface integration and proper testing

**Comment by Iliyas-shah** [comment]
Hey I would like to work on this video calling feature, could you please assign me this issue

**Comment by sai2003a** [comment]
@Iliyas-shah ok i will assign  you this feature

**Comment by Iliyas-shah** [comment]
@sai2003a Thanks
